<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1576065984231' stop='1576066148901'>
    <name>ENDEVOUR CYPRESS SITE TEST AUTOMATION</name>
    <title>ENDEVOUR CYPRESS SITE TEST AUTOMATION</title>
    <test-cases>
        <test-case start='1576065984232' status='failed' stop='1576066061857'>
            <name>verify that page content of a Cypress web site : FirstDataSets</name>
            <title>verify that page content of a Cypress web site : FirstDataSets</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at ontimeout (timers.js:436:11)
                    at tryOnTimeout (timers.js:300:5)
                    at listOnTimeout (timers.js:263:5)
                    at Timer.processTimers (timers.js:223:10)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1576066061858' status='failed' stop='1576066109627'>
            <name>verify that page content of a Cypress web site : SecondDataSets</name>
            <title>verify that page content of a Cypress web site : SecondDataSets</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>TimeoutError: Wait timed out after 12086ms</message>
                <stack-trace>TimeoutError: Wait timed out after 12086ms
                    at C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2201:17
                    at ManagedPromise.invokeCallback_ (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at asyncRun (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
                    at C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
                    at process._tickCallback (internal/process/next_tick.js:68:7)
                From: Task: &lt;anonymous wait>
                    at scheduleWait (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2188:20)
                    at ControlFlow.wait (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2517:12)
                    at Driver.wait (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:934:29)
                    at run (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\built\browser.js:59:33)
                    at ProtractorBrowser.to.(anonymous function) [as wait] (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\built\browser.js:67:16)
                    at CypressURL_Content.moveToWindowPopUp (C:\Users\Owner\Desktop\EndevourCucumberDemo2\pages\CypressURL_Content.js:9:17)
                    at UserContext.&lt;anonymous> (C:\Users\Owner\Desktop\EndevourCucumberDemo2\specDefs\urlContentVerification_spec.js:56:32)
                    at process._tickCallback (internal/process/next_tick.js:68:7)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1576066109628' status='failed' stop='1576066148898'>
            <name>verify that page content of a Cypress web site : ThirdDataSets</name>
            <title>verify that page content of a Cypress web site : ThirdDataSets</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>TimeoutError: Wait timed out after 12141ms</message>
                <stack-trace>TimeoutError: Wait timed out after 12141ms
                    at C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2201:17
                    at ManagedPromise.invokeCallback_ (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at asyncRun (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
                    at C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
                    at process._tickCallback (internal/process/next_tick.js:68:7)
                From: Task: &lt;anonymous wait>
                    at scheduleWait (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2188:20)
                    at ControlFlow.wait (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2517:12)
                    at Driver.wait (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:934:29)
                    at run (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\built\browser.js:59:33)
                    at ProtractorBrowser.to.(anonymous function) [as wait] (C:\Users\Owner\AppData\Roaming\npm\node_modules\protractor\built\browser.js:67:16)
                    at CypressURL_Content.moveToWindowPopUp (C:\Users\Owner\Desktop\EndevourCucumberDemo2\pages\CypressURL_Content.js:9:17)
                    at UserContext.&lt;anonymous> (C:\Users\Owner\Desktop\EndevourCucumberDemo2\specDefs\urlContentVerification_spec.js:56:32)
                    at process._tickCallback (internal/process/next_tick.js:68:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>